# Site settings
title: manojmahapatra.github.io
email: mahapatra.manoj@hotmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manojmahapatra.github.io" # the base hostname & protocol for your site
twitter_username: 0manoj1
github_username:  manojmahapatra

# Build settings
markdown: kramdown
